title: Home
author: Kyle Chang
email: iiii110270@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A place to store all my programming practices.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  iiii110270 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
